name = "TrajectoryOptimization"
uuid = "c79d492b-0548-5874-b488-5a62c1d9d0ca"
version = "0.7.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
RobotZoo = "74be38bb-dcc2-4b9e-baf3-d6373cd95f10"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocStringExtensions = "0.8"
FiniteDiff = "2"
ForwardDiff = "0.10"
RobotDynamics = "0.4.3"
RobotZoo = "0.3"
Rotations = "~1.0"
StaticArrays = "1"
julia = "1"
